CREATE TABLE QuestionUser (
Id INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
UserId BIGINT  NOT NULL,
QuestionId BIGINT NOT NULL,
Count INT
FOREIGN KEY (UserId) REFERENCES Users(Id),
FOREIGN KEY (QuestionId) REFERENCES Question(Id)
);
